### ISSUE TITLE
Scroll down deployment progress output window

### ISSUE THREAD

**Issue by ezaquarii** [ezaquarii/vpn-at-home#26]
When new output arrives, check if dialog is scrolled to the bottom and scroll again after new content is added.

Pseudocode:
```
if already_scrolled_to_bottom:
    add_new_content
    scroll_to_bottom
else:
    add_new_content
    leave_scroll_position_intact
```

**Comment by arpreq** [comment]
Hi,

I attempted to look into this today but I ran into a strange problem: None of the changes I make to the frontend source take effect, even after a `make devel_frontend` or
```
make distclean
make devel
```
I'm trying to edit `DeploymentDialog.vue` in /frontend/src/components/

Interestingly, deleting this file does make the compilation fail, but leaving the file and deleting its contents leads to no changes as if the original version is still loaded. I tried using two different browsers in case it was somehow cached but they both loaded the original frontend.

Am I doing something wrong? I've never worked in an environment like this before.

Thanks.

**Comment by ezaquarii** [comment]
Hi,

Thank you for your contribution.

First, make sure that `data/settings.json` has `"development": true` flag set. `"debug_toolbar_enabled": true` might also be helpful as it enabled Django Debug Toolbar that gives you some insights into Django settings.

Now, to the point.

Frontend is served from `backend/vpnathome/apps/frontend/{static,templates}` **by default**.
In development mode (`make devel` sets dev mode in `settings.json`), directory `frontend/dist` is added to Django config with higher priority. Pseudo-code:

```
if devel frontend build present in frontned/dist:
    serve devel frontend from frontend/dist/
else:
    serve prod frontnend from backend/vpnathome/apps/frontend/

To use a development frontend you must re-build it first:

`npm run-script build-watch`

Then simply reload the page - the app will pick it up and you'll see "development" in web browser title bar - sign that `index.html` template is taken from your fresh build.

Once you're done, just leave it there. I'll update prod frontend files in `backend` once, before release.

Also, pls keep commits for `backend` and `frontend` separate - they should be modified separately and I don't want to minimize coupling.

**Comment by ezaquarii** [comment]
If you are curious where the switch of frontend happens, check the logic is in `backend/vpnathome/settings/{static.py,templates.py}` files.

**Comment by arpreq** [comment]
Wow! Thank you for the detailed explanation! It does make more sense now; though I thought I may have been going insane before.

Now I am able to see changes that I make in the src folder. I'll send the pull request once I make and test the actual changes.

Thanks again!
