### ISSUE TITLE
Test login credentials do not work

### ISSUE THREAD

**Issue by LukasWerfel** [ezaquarii/vpn-at-home#29]
The login [credentials of the readme](https://github.com/ezaquarii/vpn-at-home#configuration) do not work in dev mode. 
Server responds with a 400 and `Enter a valid email address`.

**Comment by ezaquarii** [comment]
Can you paste your `pip freeze`? It works for me and the only thing that comes to my mind is updated validator in Django Rest Framework became stricter.

Also, `./bin/set_admin --help` to the rescue.

**Comment by ezaquarii** [comment]
`admin@localhost` or `admin@localdomain` (the latter results in 400)

**Comment by LukasWerfel** [comment]
Ì was trying with `admin@localhost`. 
Just changed it in the makerfile to admin@localhost.local and that worked.

I am not familiar with pip, but when I execute `pip freeze` I get
> bash: pip: command not found

**Comment by LukasWerfel** [comment]
I use Ubuntu 18
```
asgiref==2.3.2
asn1crypto==0.24.0
async-timeout==3.0.0
attrs==18.2.0
autobahn==18.9.2
Automat==0.7.0
backcall==0.1.0
cffi==1.11.5
channels==2.1.3
constantly==15.1.0
coverage==4.5.1
cryptography==2.3.1
daphne==2.2.2
decorator==4.3.0
Django==2.1.2
django-constance==2.2.0
django-cors-headers==2.3.0
django-debug-toolbar==1.9.1
django-model-utils==3.1.2
django-picklefield==1.0.0
django-x509==0.4.1
djangorestframework==3.8.2
docutils==0.14
hyperlink==18.0.0
idna==2.7
incremental==17.5.0
ipdb==0.11
ipython==6.4.0
ipython-genutils==0.2.0
jedi==0.12.1
jsonfield==2.0.2
parso==0.3.1
pexpect==4.6.0
pickleshare==0.7.4
prompt-toolkit==1.0.15
ptyprocess==0.6.0
pyasn1==0.4.4
pyasn1-modules==0.2.2
pycparser==2.18
Pygments==2.2.0
PyHamcrest==1.9.0
pyOpenSSL==17.5.0
pytz==2018.5
service-identity==17.0.0
simplegeneric==0.8.1
six==1.11.0
sqlparse==0.2.4
traitlets==4.3.2
Twisted==18.7.0
txaio==18.8.1
uWSGI==2.0.17.1
wcwidth==0.1.7
zope.interface==4.5.0
```

**Comment by ezaquarii** [comment]
This requires more investigation. DRF has domain_whitelist = ['localhost']:

https://github.com/django/django/blob/6fe9c45b725cd21eacbb50263bd3449e1a3edf17/django/core/validators.py#L179

so it should just work.

**Comment by ezaquarii** [comment]
Cannot reproduce.
