### ISSUE TITLE
[frontend] Fix onStart callback being not called

### ISSUE THREAD

**Issue by arpreq** [ezaquarii/vpn-at-home#39]
`deployment.js` checks for `json.status === 'start'` when it should check for `json.status === 'started'`

As it is now, the `onStart` callback is never called.

**Comment by ezaquarii** [comment]
Fixed: 0ecc88da6c71d6a531f32719bfa6ecde0cee444d

**Comment by ezaquarii** [comment]
I'll leave this issue closed and re-open a new one.

**Comment by ezaquarii** [comment]
xref https://github.com/ezaquarii/vpn-at-home/issues/41
