### ISSUE TITLE
One-Click AWS Deploy via CloudFormation

### ISSUE THREAD

**Issue by bwagner5** [ezaquarii/vpn-at-home#51]
A lot of users will inevitably use AWS to host their VPS for the VPN. It would also be interesting to connect an AWS network with your home network as an extension. 

I would propose a CloudFormation template to be built which stands up the infrastructure (VPC, public/private subnets, IGW, Route 53 Dynamic DNS, ASG, EC2 instance) for a 1-click deployment to AWS. 

The ansible playbooks can still be used to deploy to the EC2 Instance.  Once the CF template is completed, this could also be advertised on the AWS Marketplace.

**Comment by ezaquarii** [comment]
I believe that current playbook can be used with EC2 instance. It should in fact work with any Ubuntu 18.04 or OpenBSD 6.4 VPS OOTB, regardless of the hosting company.

I does not instantiate the VPS however, although Ansible has some modules to handle that. I havne't explored it however.

**Comment by bwagner5** [comment]
**Who is the target audience (ASG sounds a bit enterprise-y and this is not my aspiration)**
I'm not suggesting any enterprise features. ASG is a free service on AWS that will maintain a group of servers (or 1). In this case, I would use it to maintain a fleet of 1 server for the VPS VPN instance. Since these are cloud machines, they can die (just like any server), so it will just boot up another one if that were to happen. 

**How do you see the user interface for it?**

The user interface can be exposed via a public IP w/ a firewall in-front of it allowing either SSH or HTTP from the user's home WAN public IP (this can be closed off after the VPN is up) 

User Interaction Story:

-> Existing AWS Customer wants a VPN for their home network
-> Clone down "vpc-at-home" repo and build it which will now generate a cloudformation template zip file 
-> The user will go to CloudFormation on AWS and upload the zip file. 
-> CloudFormation will then ask a few questions about the home network WAN. 

**Do you need proprietary tools? It must be packaged and built on Launchpad.**

No proprietary tools needed. The CloudFormation template is simply a YAML or JSON file which can be built via vanilla python or ruby template builds.

**What is the estimated maintenance effort for this feature?**
I would expect maintenance to be very low and maybe non-existent. The infrastructure definition should not change. It will always be setting up a default network and launching a single instance.

**Comment by ezaquarii** [comment]
> The user interface can be exposed via a public IP w/ a firewall in-front of it allowing either
> SSH or HTTP from the user's home WAN public IP (this can be closed off after the VPN is up)

The user interface should not be hanging on public IP as the app has root access to the deployment machine. It is probably just a matter of time until the VPS starts digging bitcoins and I do not want to be the one being blamed for that. ;-)

> The user will go to CloudFormation on AWS and upload the zip file.
> CloudFormation will then ask a few questions about the home network WAN.

It looks for me like you want to automate the deployment of VPN@Home itself, not the actual OpenVPN instance and I see this effort being completely orthogonal to VPN@Home goals. 

If you stick with Ubuntu derivative than you don't need to build VPN@Home as it is already packaged and I'm committed to maintaining stable packages with decent scripting support to help any automated deployment efforts.

I'm perfectly happy to assist you with any knowledge or troubleshooting while pursuing it.

Please note that the scenario you just described might be already covered by OpenVPN Access Server Cloud.

**Comment by ezaquarii** [comment]
Sorry, I'm a bit confused about the user journey here. 

If you just want to generate a cloud formation template from VPN server config, then this is rather trivial to do and I think we can add some generic "my own template" feature to cover this.

**Comment by bwagner5** [comment]
the zip file is just what the template is uploaded as to the CloudFormation service. It will just define infrastructure (1 server, maybe a startup script derived from the ansible playbook if we wanted it completely 1-click). 

A template is all I'm recommending which can be statically generated at build time. Hope that clears up confusion on the user journey.

**Comment by ezaquarii** [comment]
I'm not sure what is the value of build-time generated template:

1) the app does not contain any valuable information at that time
2) deb package is the recommended way of deploying the application

Am I still missing something here?

**Comment by bwagner5** [comment]
ah I see your point. Didn't see that it was a deb installation... 

Seems a static built template added to the repo would be trivial.

**Comment by ezaquarii** [comment]
It would be trivial to add a file, but I have no bandwidth to keep in tested through releases.
