### ISSUE TITLE
how to use the windows ?

### ISSUE THREAD

**Issue by oylemesn** [ezaquarii/vpn-at-home#65]
how to use the windows ?

**Comment by ezaquarii** [comment]
@oylemesn I'm not entirely sure what did you mean? Microsoft Windows?

If so, I'm not using Microsoft Windows and I have no capacity to support it on that platform. But WLS should do the trick, as it's based on Ubuntu.

**Comment by ezaquarii** [comment]
Closing it for now. Please feel free to re-open if you have more questions.
