### ISSUE TITLE
No module named 'ansible'

### ISSUE THREAD

**Issue by Shane19822** [ezaquarii/vpn-at-home#70]
hi,

i used fresh ubuntu 20.04 server version but when i deply server there is issue see below 

Traceback (most recent call last):
File "/usr/bin/ansible-playbook", line 34, in <module>
from ansible import context
ModuleNotFoundError: No module named 'ansible'
Deployment finishe

Thanks

**Comment by ezaquarii** [comment]
@Shane19822 Thanks for the report. I'm no longer supporting this software.
